---
name: Run Unit Tests

on: 
  push :
    branches :
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docker
        run: |
          docker build -t kargotech/excellerate-pipeline/python
      - name: Push docker
        run: |
          docker tag temp/build yollafrdl/excellerate:latest
          docker tag temp/build yollafrdl/excellerate:${{ github.sha }}
          docker push yollafrdl/excellerate:latest
          docker push yollafrdl/excellerate:${{ github.sha }}
